# Common configuration.
AllCops:
  # Include common Ruby source files.
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'db/**/*'
    - 'backup/**/*'
    - 'bundler_stubs/**/*'
    - 'log/**/*'
    - '.bundle/**/*'
    - 'config/**/*'
    - 'config/environments/**'
    - 'config/application.rb'
    - 'bin/**/*'
    - 'temp/**/*'
    - 'db/schema.rb'
    - 'spec/support/**/*'
    - 'app/controllers/concerns/broadcasted.rb'
    - 'Gemfile.lock'
    - 'Gemfile'
    - 'features/step_definitions/email_steps.rb'

Documentation:
  Enabled: false
Metrics/LineLength:
  Max: 120
Style/FrozenStringLiteralComment:
  Enabled: false
Style/BarePercentLiterals:
  Enabled: false
Style/PercentLiteralDelimiters:
  Enabled: false
Style/UnneededPercentQ:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false
Style/OptionalArguments:
  Enabled: false
Style/AsciiComments:
  Enabled: false
